export const GET_INITIAL_DATA = 'GET_INITIAL_DATA';
export const RECEIVED_INITIAL_DATA = 'RECEIVED_INITIAL_DATA';
export const RECEIVED_INITIAL_DATA_ERROR = 'RECEIVED_INITIAL_DATA_ERROR';

export const GET_PROPERTIES = 'GET_PROPERTIES';
export const RECEIVED_PROPERTIES = 'RECEIVED_PROPERTIES';
export const RECEIVED_PROPERTIES_ERROR = 'RECEIVED_PROPERTIES_ERROR';

export const GET_SEARCH_PROPERTIES = 'GET_SEARCH_PROPERTIES';
export const RECEIVED_SEARCH_PROPERTIES = 'RECEIVED_SEARCH_PROPERTIES';
export const RECEIVED_SEARCH_PROPERTIES_ERROR = 'RECEIVED_SEARCH_PROPERTIES_ERROR';

export const SAVE_SELECTED_PROPERTIES = 'SAVE_SELECTED_PROPERTIES';
export const RECEIVED_SAVE_PROPERTIES = 'RECEIVED_SAVE_PROPERTIES';
export const RECEIVED_SAVE_PROPERTIES_ERROR = 'RECEIVED_SAVE_PROPERTIES_ERROR';

export const FORM_SEARCH_FILTER = 'FORM_SEARCH_FILTER';
export const FORM_PROPERTY_LIST = 'FORM_PROPERTY_LIST';
